# Generated by Django 6.0.2 on 2026-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('priority_hint', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('channel', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
