# Generated by Django 6.0.2 on 2026-02-27 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('NOW', 'Now'), ('LATER', 'Later'), ('NEVER', 'Never')], max_length=6)),
                ('explanation', models.TextField()),
                ('duplicate_result', models.CharField(blank=True, max_length=10, null=True)),
                ('rules_triggered', models.JSONField(blank=True, default=dict)),
                ('fatigue_snapshot', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.notificationevent')),
            ],
        ),
    ]
