# Generated by Django 6.0.2 on 2026-02-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('DELIVERED', 'Delivered'), ('DROPPED', 'Dropped')], default='PENDING', max_length=10)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred', to='api.notificationevent')),
            ],
        ),
    ]
